### ISSUE TITLE
First Version

### ISSUE THREAD

**Issue by cortner** [ACEsuit/DecoratedParticles.jl#1]
@zhanglw0521 and @ CheukHinHoJerry -- I've copy-pasted the ACE.jl code, and fixed a few things so that the tests pass. I didn't yet transfer the documentation (such as it is) but Liwei understands this reasonably well I think. Please see if this suits your purpose. As soon as you think it is usable I can tag a first version.

**Comment by zhanglw0521** [comment]
I think it is time to tag the first version unless @CheukHinHoJerry has some other thoughts - the usability of this package can actually be checked by the latest PR of EQM.

**Comment by CheukHinHoJerry** [comment]
I will take a look tmr.
